// This file is auto-generated by timber.js route map codegen.
// Do not edit manually. Regenerated on build and in dev mode.

export {};

type _TimberResolveSegmentField<Def, K extends string, F> =
  Def extends import('@timber-js/app/segment-params').ParamsDefinition<infer T>
    ? K extends keyof T ? T[K] : F
    : F;

declare module '@timber-js/app' {
  interface Routes {
    '/': {
      segmentParams: {}
      searchParams: {}
    }
    '/blog/hello': {
      segmentParams: {}
      searchParams: {}
    }
  }
}

declare module '@timber-js/app/client' {
  import type { SearchParamsDefinition, SetParams, QueryStatesOptions, SearchParamCodec } from '@timber-js/app/search-params'

  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/blog/hello'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<T extends Record<string, unknown>>(codecs: { [K in keyof T]: SearchParamCodec<T[K]> }, options?: QueryStatesOptions): [T, SetParams<T>]

  // Typed Link overloads — per-route (block 1 / emitted first)
  interface LinkFunction {
    (
      props:
        | (Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & { prefetch?: boolean; scroll?: boolean; preserveSearchParams?: true | string[]; onNavigate?: import('./client/link.js').OnNavigateHandler; children?: import('react').ReactNode } & { href: '/'; segmentParams?: Record<string, unknown>; searchParams?: Record<string, unknown> })
        | (Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & { prefetch?: boolean; scroll?: boolean; preserveSearchParams?: true | string[]; onNavigate?: import('./client/link.js').OnNavigateHandler; children?: import('react').ReactNode } & { href: '/blog/hello'; segmentParams?: Record<string, unknown>; searchParams?: Record<string, unknown> })
    ): import('react').JSX.Element
  }

}

declare module '@timber-js/app/client' {
  import type { SearchParamsDefinition } from '@timber-js/app/search-params'

  // Typed Link overloads — catch-all (block 2 / emitted second)
  interface LinkFunction {
    (props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & { prefetch?: boolean; scroll?: boolean; preserveSearchParams?: true | string[]; onNavigate?: import('./client/link.js').OnNavigateHandler; children?: import('react').ReactNode } & {
      href: `http://${string}` | `https://${string}` | `mailto:${string}` | `tel:${string}` | `ftp://${string}` | `//${string}` | `#${string}` | `?${string}`
      segmentParams?: Record<string, unknown>
      searchParams?: { definition: SearchParamsDefinition<Record<string, unknown>>; values: Record<string, unknown> } | Record<string, unknown>
    }): import('react').JSX.Element
    <H extends string>(
      props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & { prefetch?: boolean; scroll?: boolean; preserveSearchParams?: true | string[]; onNavigate?: import('./client/link.js').OnNavigateHandler; children?: import('react').ReactNode } & {
        href: string extends H ? H : never
        segmentParams?: Record<string, string | number | string[]>
        searchParams?: { definition: SearchParamsDefinition<Record<string, unknown>>; values: Record<string, unknown> } | Record<string, unknown>
      }
    ): import('react').JSX.Element
  }
}
